/**
 * Curated re-exports from `lucide-react`. Components should import icons from
 * here, never directly from `lucide-react`, so the design system can swap
 * icon sets later if needed and so unused icons stay tree-shakable.
 *
 * Defaults applied at the call site:
 *   - 16px for inline-with-text usage
 *   - 20px for use inside buttons
 *   - strokeWidth 1.5
 */
export {
  AlertCircle,
  AlertTriangle,
  ArrowDown,
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  ArrowUpDown,
  AtSign,
  BarChart3,
  Bell,
  Bookmark,
  Calendar,
  Check,
  CheckCircle2,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  ChevronsLeft,
  ChevronsRight,
  ChevronsUpDown,
  Circle,
  Copy,
  CornerDownLeft,
  CreditCard,
  Download,
  Edit2,
  Ellipsis,
  Eye,
  EyeOff,
  Filter,
  Folder,
  GripVertical,
  Home,
  Inbox,
  LayoutGrid,
  Lock,
  LogOut,
  HelpCircle,
  Info,
  Link2,
  Loader2,
  Mail,
  Menu,
  Minus,
  MoreHorizontal,
  Package,
  Plug,
  Plus,
  Search,
  Sparkles,
  Settings,
  Sun,
  Moon,
  Trash2,
  Upload,
  User,
  Users,
  X,
  XCircle,
  ExternalLink,
  type LucideIcon,
  type LucideProps,
} from 'lucide-react';
