/* Runs the showcase E2E suite and rewrites the generated block at the top of
 * e2e/FINDINGS.md from Playwright's JSON report, so the "current state" table
 * can never drift from the last run. Exit code is Playwright's.
 *
 *   pnpm test:e2e                 # full run, then update FINDINGS.md
 *   pnpm test:e2e docs            # args pass through to `playwright test`
 *   pnpm e2e:findings             # only rewrite the block from the last report
 *
 * The block is left alone under CI or when the run is sharded / filtered,
 * because a partial report would describe a partial suite. */

import { spawnSync } from 'node:child_process';
import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import { createRequire } from 'node:module';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(__dirname, '..');
const REPORT = path.join(ROOT, 'test-results/report.json');
const DOC = path.join(ROOT, 'e2e/FINDINGS.md');
const START = '<!-- e2e-state:start -->';
const END = '<!-- e2e-state:end -->';

interface JsonTest {
  status: 'expected' | 'unexpected' | 'flaky' | 'skipped';
}
interface JsonSpec {
  tests: JsonTest[];
}
interface JsonSuite {
  file: string;
  specs: JsonSpec[];
  suites?: JsonSuite[];
}
interface JsonReport {
  stats: { startTime: string; duration: number };
  suites: JsonSuite[];
}

interface Counts {
  tests: number;
  passed: number;
  failed: number;
  skipped: number;
}

function collect(suite: JsonSuite, into: Counts) {
  for (const spec of suite.specs) {
    for (const t of spec.tests) {
      into.tests++;
      if (t.status === 'skipped') into.skipped++;
      else if (t.status === 'unexpected') into.failed++;
      else into.passed++; // expected, or flaky (passed on retry)
    }
  }
  for (const s of suite.suites ?? []) collect(s, into);
}

const require = createRequire(import.meta.url);

/** `major.minor` of an installed package (node_modules is hoisted, so resolve). */
function version(pkg: string): string {
  const p = require.resolve(`${pkg}/package.json`);
  return JSON.parse(readFileSync(p, 'utf8')).version.replace(/\.\d+$/, '');
}

function render(report: JsonReport): string {
  const perFile = new Map<string, Counts>();
  for (const s of report.suites) {
    const c = perFile.get(s.file) ?? { tests: 0, passed: 0, failed: 0, skipped: 0 };
    collect(s, c);
    perFile.set(s.file, c);
  }
  const files = [...perFile.keys()].sort();
  const total: Counts = { tests: 0, passed: 0, failed: 0, skipped: 0 };
  const rows = files.map((f) => {
    const c = perFile.get(f)!;
    total.tests += c.tests;
    total.passed += c.passed;
    total.failed += c.failed;
    total.skipped += c.skipped;
    return [`\`${path.basename(f)}\``, c.tests, c.passed, c.failed, c.skipped];
  });
  rows.push(['**Total**', total.tests, total.passed, total.failed, total.skipped]);

  const header = ['Spec', 'Tests', 'Passed', 'Failed', 'Skipped'];
  const width = header.map((h, i) => Math.max(h.length, ...rows.map((r) => String(r[i]).length)));
  const line = (cells: (string | number)[]) =>
    '| ' +
    cells
      .map((c, i) => (i === 0 ? String(c).padEnd(width[i]) : String(c).padStart(width[i])))
      .join(' | ') +
    ' |';
  const sep =
    '| ' +
    width.map((w, i) => (i === 0 ? '-'.repeat(w) : '-'.repeat(w - 1) + ':')).join(' | ') +
    ' |';

  const date = report.stats.startTime.slice(0, 10);
  const minutes = (report.stats.duration / 60_000).toFixed(1);
  return [
    START,
    '',
    `## Current state — ${date}`,
    '',
    `Run: local, chromium (headless shell), fresh \`vite build\` of the showcase, Playwright ${version('@playwright/test')}, axe-core ${version('axe-core')}`,
    '(tags `wcag2a wcag2aa wcag21aa wcag22aa`; only `serious`/`critical` fail a test). ' +
      `${minutes} min.`,
    'Matrix: docs 1280 light+dark, 375 light; templates 320/768 light, 375/1280 light+dark.',
    '',
    line(header),
    sep,
    ...rows.map(line),
    '',
    '_Generated by `scripts/e2e-findings.ts` from `test-results/report.json`; edit the text below, not this block._',
    '',
    END,
  ].join('\n');
}

function updateDoc() {
  if (!existsSync(REPORT)) {
    console.error(
      `[e2e-findings] no report at ${path.relative(ROOT, REPORT)} — run the suite first`,
    );
    process.exit(1);
  }
  const report = JSON.parse(readFileSync(REPORT, 'utf8')) as JsonReport;
  const doc = readFileSync(DOC, 'utf8');
  const a = doc.indexOf(START);
  const b = doc.indexOf(END);
  if (a < 0 || b < 0) {
    console.error(`[e2e-findings] markers ${START} / ${END} not found in FINDINGS.md`);
    process.exit(1);
  }
  const next = doc.slice(0, a) + render(report) + doc.slice(b + END.length);
  if (next !== doc) {
    writeFileSync(DOC, next);
    console.log('[e2e-findings] FINDINGS.md updated');
  } else {
    console.log('[e2e-findings] FINDINGS.md already current');
  }
}

const args = process.argv.slice(2);
const onlyDoc = args[0] === '--doc';
if (onlyDoc) {
  updateDoc();
} else {
  const run = spawnSync('pnpm', ['exec', 'playwright', 'test', ...args], {
    cwd: ROOT,
    stdio: 'inherit',
  });
  const partial =
    process.env.CI || args.some((a) => /^--(shard|grep|g)\b|^-g$/.test(a) || !a.startsWith('-'));
  if (!partial) updateDoc();
  else console.log('[e2e-findings] partial or CI run — FINDINGS.md left as is');
  process.exit(run.status ?? 1);
}
