/**
 * Parse every component under src/components/ui/ with react-docgen-typescript
 * and emit src/showcase/registry/generated-props.ts — a typed map of
 * `{ [componentName]: PropGroup[] }`. Doc files import from there instead of
 * hand-writing the props arrays, so the docs can never drift from the
 * TypeScript interface.
 *
 * Run via `pnpm gen:props`. CI also runs it before build.
 */

import path from 'node:path';
import { fileURLToPath } from 'node:url';
import fs from 'node:fs';
import { withCustomConfig } from 'react-docgen-typescript';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(__dirname, '..');
const UI_DIR = path.join(ROOT, 'src/components/ui');
const OUTPUT = path.join(ROOT, 'src/showcase/registry/generated-props.ts');
const TSCONFIG = path.join(ROOT, 'tsconfig.json');

const parser = withCustomConfig(TSCONFIG, {
  savePropValueAsString: true,
  shouldExtractLiteralValuesFromEnum: true,
  shouldRemoveUndefinedFromOptional: true,
  // Skip props inherited from native HTML attributes — too much noise.
  propFilter: (prop) => {
    if (prop.parent) {
      const fn = prop.parent.fileName;
      if (fn.includes('node_modules/@types/react')) return false;
      if (fn.includes('node_modules/react')) return false;
    }
    return !prop.description?.startsWith('@internal');
  },
});

interface PropRow {
  name: string;
  type: string;
  default?: string;
  required?: boolean;
  description: string;
}

interface PropGroup {
  title?: string;
  rows: PropRow[];
}

function parseFile(file: string): Record<string, PropGroup[]> {
  const components = parser.parse(file);
  if (components.length === 0) return {};
  const out: Record<string, PropGroup[]> = {};
  for (const c of components) {
    const rows: PropRow[] = Object.values(c.props).map((p) => ({
      name: p.name,
      type: simplifyType(p.type?.name ?? 'unknown'),
      default: p.defaultValue?.value ?? undefined,
      required: p.required,
      description: (p.description ?? '').replace(/\s+/g, ' ').trim(),
    }));
    if (rows.length === 0) continue;
    // Sort: required first, then alphabetical.
    rows.sort((a, b) => {
      if (a.required !== b.required) return a.required ? -1 : 1;
      return a.name.localeCompare(b.name);
    });
    out[c.displayName] = [{ rows }];
  }
  return out;
}

function simplifyType(type: string): string {
  // react-docgen often spits out very long unions for ReactNode / CSSProperties.
  // Tighten the common cases so the table stays readable.
  return type
    .replace(/ReactElement<.*?, .*?>/g, 'ReactElement')
    .replace(/false \| /g, '')
    .slice(0, 240);
}

function main() {
  const files = fs
    .readdirSync(UI_DIR)
    .filter((f) => f.endsWith('.tsx') && !f.endsWith('.test.tsx'))
    .map((f) => path.join(UI_DIR, f));

  const all: Record<string, PropGroup[]> = {};
  for (const file of files) {
    try {
      const parsed = parseFile(file);
      Object.assign(all, parsed);
    } catch (err) {
      console.warn(`[gen-props] skipping ${path.basename(file)}: ${(err as Error).message}`);
    }
  }

  const sortedNames = Object.keys(all).sort();
  const json = JSON.stringify(
    Object.fromEntries(sortedNames.map((n) => [n, all[n]])),
    null,
    2,
  );

  const banner = `// AUTO-GENERATED by scripts/generate-props.ts — do not edit by hand.
// Run \`pnpm gen:props\` to refresh after changing a component's interface.
//
// Sourced from the exported props interfaces of each component under
// src/components/ui/. Native HTML attributes inherited via Omit<HTMLAttrs>
// are filtered out — only library-specific props are listed.

import type { PropGroup } from './types';

export const generatedProps: Record<string, PropGroup[]> = ${json};

/**
 * Lookup helper: returns auto-generated props for a component, or undefined
 * if the parser couldn't extract any (consumer should hand-write \`api\` then).
 */
export function getGeneratedProps(name: string): PropGroup[] | undefined {
  return generatedProps[name];
}
`;

  fs.writeFileSync(OUTPUT, banner);
  console.log(
    `[gen-props] wrote ${sortedNames.length} components → ${path.relative(ROOT, OUTPUT)}`,
  );
}

main();
